set-option -g default-command "exec /bin/bash"

set -g prefix C-space
bind C-space send-prefix
unbind C-b

set -sg escape-time 0

set-window-option -g mode-keys vi

bind c new-window -c "#{pane_current_path}"
bind - split-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
unbind %

# reload config
bind r source-file ~/.tmux.conf

# Enable mouse control (clickable windows, panes, resizable panes)
#set -g mouse-select-window on
#set -g mouse-select-pane on
#set -g mouse-resize-pane on

# vim keys <3
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g mouse on
